import type { FundPosition } from "./fund-list-data";

export { stockAccounts as fundAccounts } from "@/components/stock/stock-mock";

export const fundPositionsMock: FundPosition[] = [
  {
    id: "fund-001",
    name: "安聯台灣科技基金 A",
    symbol: "ALTW-A",
    fundHouse: "安聯投信",
    risk: "RR4",
    dividendMode: "accumulation",
    currency: "TWD",
    costAmount: 320000,
    marketValue: 362500,
    unrealizedReturnRate: 13.28125,
  },
  {
    id: "fund-002",
    name: "富蘭克林穩定月收益基金",
    symbol: "FRK-STB",
    fundHouse: "富蘭克林",
    risk: "RR3",
    dividendMode: "cash",
    currency: "USD",
    costAmount: 9800,
    marketValue: 10340,
    unrealizedReturnRate: 5.510204081632653,
  },
  {
    id: "fund-003",
    name: "貝萊德世界能源基金",
    symbol: "BLK-ENG",
    fundHouse: "貝萊德",
    risk: "RR5",
    dividendMode: "accumulation",
    currency: "USD",
    costAmount: 12500,
    marketValue: 11780,
    unrealizedReturnRate: -5.76,
  },
  {
    id: "fund-004",
    name: "國泰全球 ESG 永續成長基金",
    symbol: "CT-ESG",
    fundHouse: "國泰投信",
    risk: "RR3",
    dividendMode: "accumulation",
    currency: "TWD",
    costAmount: 210000,
    marketValue: 224200,
    unrealizedReturnRate: 6.761904761904762,
  },
  {
    id: "fund-005",
    name: "野村日本策略價值基金",
    symbol: "NMR-JP",
    fundHouse: "野村投信",
    risk: "RR4",
    dividendMode: "cash",
    currency: "TWD",
    costAmount: 160000,
    marketValue: 156900,
    unrealizedReturnRate: -1.9375,
  },
];
