import type { FundPosition } from "./fund-list-data";

export const fundPositionsMock: FundPosition[] = [
  {
    id: "fund-001",
    name: "安聯台灣科技基金 A",
    symbol: "ALTW-A",
    fundHouse: "安聯投信",
    risk: "RR4",
    dividendMode: "reinvest",
    currency: "TWD",
    costAmount: 320000,
    marketValue: 362500,
    return1m: 3.6,
    return1y: 17.4,
  },
  {
    id: "fund-002",
    name: "富蘭克林穩定月收益基金",
    symbol: "FRK-STB",
    fundHouse: "富蘭克林",
    risk: "RR3",
    dividendMode: "cash",
    currency: "USD",
    costAmount: 9800,
    marketValue: 10340,
    return1m: 1.1,
    return1y: 7.8,
  },
  {
    id: "fund-003",
    name: "貝萊德世界能源基金",
    symbol: "BLK-ENG",
    fundHouse: "貝萊德",
    risk: "RR5",
    dividendMode: "reinvest",
    currency: "USD",
    costAmount: 12500,
    marketValue: 11780,
    return1m: -2.3,
    return1y: 4.2,
  },
  {
    id: "fund-004",
    name: "國泰全球 ESG 永續成長基金",
    symbol: "CT-ESG",
    fundHouse: "國泰投信",
    risk: "RR3",
    dividendMode: "reinvest",
    currency: "TWD",
    costAmount: 210000,
    marketValue: 224200,
    return1m: 2.2,
    return1y: 10.4,
  },
  {
    id: "fund-005",
    name: "野村日本策略價值基金",
    symbol: "NMR-JP",
    fundHouse: "野村投信",
    risk: "RR4",
    dividendMode: "cash",
    currency: "TWD",
    costAmount: 160000,
    marketValue: 156900,
    return1m: -0.8,
    return1y: 5.6,
  },
];
